### ISSUE TITLE
漢数字を含む住所文字でエラーを起こすことがある

### ISSUE THREAD

**Issue by koswatana** [digital-go-jp/abr-geocoder#95]
```
% docker run --rm -v ${HOME}/Work/ba000001:/root/.abr-geocoder abrg /bin/bash -c 'echo "愛知県豊田市西丹波町九九十"|abrg -'|jq .
/usr/local/lib/node_modules/@digital-go-jp/abr-geocoder/node_modules/@geolonia/japanese-numeral/dist/index.js:26
            throw new TypeError('The attribute of kanji2number() must be a Japanese numeral as integer.');
                  ^

TypeError: The attribute of kanji2number() must be a Japanese numeral as integer.
    at kanji2number (/usr/local/lib/node_modules/@digital-go-jp/abr-geocoder/node_modules/@geolonia/japanese-numeral/dist/index.js:26:19)
    at kan2num (/usr/local/lib/node_modules/@digital-go-jp/abr-geocoder/build/domain/kan2num.js:8:86)
    at /usr/local/lib/node_modules/@digital-go-jp/abr-geocoder/build/controller/geocode/step5-transform.js:59:42
    at [Symbol.replace] (<anonymous>)
    at String.replace (<anonymous>)
    at normalization (/usr/local/lib/node_modules/@digital-go-jp/abr-geocoder/build/controller/geocode/step5-transform.js:58:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.18.2
```

**Comment by koswatana** [comment]
https://github.com/geolonia/normalize-japanese-addresses/issues/215

**Comment by maskatsum** [comment]
開発中のv2では、normalize-japanese-addressesは使用を取りやめました

**Comment by maskatsum** [comment]
v2.0.0 で検証。エラーは発生せず、適切に「西丹波町」までマッチングできている

```
[
  {
    "query": {
      "input": "愛知県豊田市西丹波町九九十"
    },
    "result": {
      "output": "愛知県豊田市西丹波町九九十",
      "other": "九九十",
      "score": 1,
      "match_level": "machiaza_detail",
      "coordinate_level": "machiaza_detail",
      "lat": 35.237834,
      "lon": 137.328839,
      "lg_code": "232114",
      "machiaza_id": "0339000",
      "rsdt_addr_flg": 0,
      "blk_id": null,
      "rsdt_id": null,
      "rsdt2_id": null,
      "prc_id": null,
      "pref": "愛知県",
      "county": null,
      "city": "豊田市",
      "ward": null,
      "oaza_cho": "西丹波町",
      "chome": null,
      "koaza": null,
      "blk_num": null,
      "rsdt_num": null,
      "rsdt_num2": null,
      "prc_num1": null,
      "prc_num2": null,
      "prc_num3": null
    },
    "debug": {
      "pref_key": 5859428,
      "city_key": 3587987522,
      "town_key": 472652788,
      "spendTime": "0.05"
    }
  }
]
```

**Comment by koswatana** [comment]
% duckdb -markdown ./abrg.duckdb "SELECT * FROM cache_basic WHERE koaza LIKE '%三五十%'"              
| categories | pref_code | lg_code | machiaza_id | rsdt_addr_flg |  pref  | county |  city  | ward | kyoto_street | oaza_cho | chome | koaza  | machiaza_dist | standardized_address |
|------------|----------:|---------|-------------|--------------:|--------|--------|--------|------|--------------|----------|-------|--------|---------------|----------------------|
| town       | 23        | 232114  | 0339114     | 0             | 愛知県 | NULL   | 豊田市 | NULL | NULL         | 西丹波町 | NULL  | 三五十 | NULL          | 豊田市西丹波町3510   |
