### ISSUE TITLE
fuzzyで複数文字指定した場合のエラー

### ISSUE THREAD

**Issue by maskatsum** [digital-go-jp/abr-geocoder#98]
`fuzzy`に複数文字が与えられたとき、エラーになる（らしい）

```
echo "福島県いわき市山玉 町脇川" | npx ts-node src/cli/cli.ts --fuzzy "????" -f json - | jq .
[error] 入力ファイルが見つかりませんでした e [YError]: 入力ファイルが見つかりませんでした
    at /workspaces/abr-geocoder/node_modules/yargs/build/index.cjs:1:32062
    at j (/workspaces/abr-geocoder/node_modules/yargs/build/index.cjs:1:4977)
    at /workspaces/abr-geocoder/node_modules/yargs/build/index.cjs:1:31877
    at /workspaces/abr-geocoder/node_modules/yargs/build/index.cjs:1:4778
    at Array.reduce (<anonymous>)
    at C (/workspaces/abr-geocoder/node_modules/yargs/build/index.cjs:1:4576)
    at _.applyMiddlewareAndGetResult (/workspaces/abr-geocoder/node_modules/yargs/build/index.cjs:1:9511)
    at _.runCommand (/workspaces/abr-geocoder/node_modules/yargs/build/index.cjs:1:7231)
    at te.[runYargsParserAndExecuteCommands] (/workspaces/abr-geocoder/node_modules/yargs/build/index.cjs:1:58912)
    at te.parse (/workspaces/abr-geocoder/node_modules/yargs/build/index.cjs:1:40478)
```

**Comment by koswatana** [comment]
```
root@e978b42eaea7:/workspaces/abr-geocoder# echo "東京都千?田区霞が関2－1－2"|npx ts-node ./src/cli/cli.ts - --fuzzy ?
[{"query":{"input":"東京都千?田区霞が関2－1－2"},"result":{"output":"東京都千代田区霞が関二丁目1-2","prefecture":"東京都","match_level":7,"city":"千代田区","town":"霞が関二丁目","town_id":"0002002","lg_code":"131016","other":"-2","lat":35.676192,"lon":139.751131,"block":"1","block_id":"001"}}]
root@e978b42eaea7:/workspaces/abr-geocoder# echo "東京都千?田区霞が関2－1－2"|npx ts-node ./src/cli/cli.ts - --fuzzy ??
root@e978b42eaea7:/workspaces/abr-geocoder# echo "東京都千??田区霞が関2－1－2"|npx ts-node ./src/cli/cli.ts - --fuzzy ??
```

**Comment by koswatana** [comment]
- 2文字だと`??`というファイルが作られてる

```
root@e978b42eaea7:/workspaces/abr-geocoder# echo "東京都千??田区霞が関2－1－2"|npx ts-node ./src/cli/cli.ts - --fuzzy ??
root@e978b42eaea7:/workspaces/abr-geocoder# ls -al ??
-rw-r--r-- 1 root root 219  2月  9 11:20 '??'
root@e978b42eaea7:/workspaces/abr-geocoder# cat ??
[{"query":{"input":"東京都千??田区霞が関2－1－2"},"result":{"output":"東京都千??田区霞が関2-1-2","prefecture":"東京都","match_level":1,"other":"千??田区霞が関2-1-2","lat":null,"lon":null}}]
```

- 3文字以上だとエラー
```
root@e978b42eaea7:/workspaces/abr-geocoder# echo "東京都千???田区霞が関2－1－2"|npx ts-node ./src/cli/cli.ts - --fuzzy ???
[error] EISDIR: illegal operation on a directory, open 'src' [Error: EISDIR: illegal operation on a directory, open 'src'] {
  errno: -21,
  code: 'EISDIR',
  syscall: 'open',
  path: 'src'
}
```

**Comment by koswatana** [comment]
- 2文字のときは期待通りに動作するようになった
```
echo "東京都千?田区霞が関2－1－2"|npx ts-node ./src/cli/cli.ts - --fuzzy ??
Original processArgv: [
  '/workspaces/abr-geocoder/node_modules/.bin/ts-node',
  '/workspaces/abr-geocoder/src/cli/cli.ts',
  '-',
  '--fuzzy',
  '??'
]
Processing arg: /workspaces/abr-geocoder/node_modules/.bin/ts-node
Processing arg: /workspaces/abr-geocoder/src/cli/cli.ts
Processing arg: -
Processing arg: --fuzzy
Processing arg: ??
Stack after processing all args: [
  ' ', '/', 'w', 'o', 'r', 'k', 's', 'p', 'a', 'c', 'e', 's',
  '/', 'a', 'b', 'r', '-', 'g', 'e', 'o', 'c', 'o', 'd', 'e',
  'r', '/', 'n', 'o', 'd', 'e', '_', 'm', 'o', 'd', 'u', 'l',
  'e', 's', '/', '.', 'b', 'i', 'n', '/', 't', 's', '-', 'n',
  'o', 'd', 'e', ' ', '/', 'w', 'o', 'r', 'k', 's', 'p', 'a',
  'c', 'e', 's', '/', 'a', 'b', 'r', '-', 'g', 'e', 'o', 'c',
  'o', 'd', 'e', 'r', '/', 's', 'r', 'c', '/', 'c', 'l', 'i',
  '/', 'c', 'l', 'i', '.', 't', 's', ' ', '-', ' ', '-', '-',
  'f', 'u', 'z', 'z',
  ... 5 more items
]
Parsed word: ??
Parsed word: --fuzzy
Fuzzy option detected
result: [ '??' ]
Parsed word: -
Parsed word: /workspaces/abr-geocoder/src/cli/cli.ts
Parsed word: /workspaces/abr-geocoder/node_modules/.bin/ts-node
Final parsed args: [
  '/workspaces/abr-geocoder/node_modules/.bin/ts-node',
  '/workspaces/abr-geocoder/src/cli/cli.ts',
  '<stdin>',
  '--fuzzy',
  '??'
]
```

- 3文字のときにエラーがでる
```
echo "東京都千?田区霞が関2－1－2"|npx ts-node ./src/cli/cli.ts - --fuzzy "???"
Original processArgv: [
  '/workspaces/abr-geocoder/node_modules/.bin/ts-node',
  '/workspaces/abr-geocoder/src/cli/cli.ts',
  '-',
  '--fuzzy',
  '???'
]
Processing arg: /workspaces/abr-geocoder/node_modules/.bin/ts-node
Processing arg: /workspaces/abr-geocoder/src/cli/cli.ts
Processing arg: -
Processing arg: --fuzzy
Processing arg: ???
Stack after processing all args: [
  ' ', '/', 'w', 'o', 'r', 'k', 's', 'p', 'a', 'c', 'e', 's',
  '/', 'a', 'b', 'r', '-', 'g', 'e', 'o', 'c', 'o', 'd', 'e',
  'r', '/', 'n', 'o', 'd', 'e', '_', 'm', 'o', 'd', 'u', 'l',
  'e', 's', '/', '.', 'b', 'i', 'n', '/', 't', 's', '-', 'n',
  'o', 'd', 'e', ' ', '/', 'w', 'o', 'r', 'k', 's', 'p', 'a',
  'c', 'e', 's', '/', 'a', 'b', 'r', '-', 'g', 'e', 'o', 'c',
  'o', 'd', 'e', 'r', '/', 's', 'r', 'c', '/', 'c', 'l', 'i',
  '/', 'c', 'l', 'i', '.', 't', 's', ' ', '-', ' ', '-', '-',
  'f', 'u', 'z', 'z',
  ... 6 more items
]
Parsed word: ???
Parsed word: --fuzzy
Fuzzy option detected
result: [ '???' ]
Parsed word: -
Parsed word: /workspaces/abr-geocoder/src/cli/cli.ts
Parsed word: /workspaces/abr-geocoder/node_modules/.bin/ts-node
Final parsed args: [
  '/workspaces/abr-geocoder/node_modules/.bin/ts-node',
  '/workspaces/abr-geocoder/src/cli/cli.ts',
  '<stdin>',
  '--fuzzy',
  '???'
]
```

**Comment by koswatana** [comment]
> * 3文字のときにエラーがでる
> 
> ```
> echo "東京都千?田区霞が関2－1－2"|npx ts-node ./src/cli/cli.ts - --fuzzy "???"
> Original processArgv: [
>   '/workspaces/abr-geocoder/node_modules/.bin/ts-node',
>   '/workspaces/abr-geocoder/src/cli/cli.ts',
>   '-',
>   '--fuzzy',
>   '???'
> ]
> Processing arg: /workspaces/abr-geocoder/node_modules/.bin/ts-node
> Processing arg: /workspaces/abr-geocoder/src/cli/cli.ts
> Processing arg: -
> Processing arg: --fuzzy
> Processing arg: ???
> Stack after processing all args: [
>   ' ', '/', 'w', 'o', 'r', 'k', 's', 'p', 'a', 'c', 'e', 's',
>   '/', 'a', 'b', 'r', '-', 'g', 'e', 'o', 'c', 'o', 'd', 'e',
>   'r', '/', 'n', 'o', 'd', 'e', '_', 'm', 'o', 'd', 'u', 'l',
>   'e', 's', '/', '.', 'b', 'i', 'n', '/', 't', 's', '-', 'n',
>   'o', 'd', 'e', ' ', '/', 'w', 'o', 'r', 'k', 's', 'p', 'a',
>   'c', 'e', 's', '/', 'a', 'b', 'r', '-', 'g', 'e', 'o', 'c',
>   'o', 'd', 'e', 'r', '/', 's', 'r', 'c', '/', 'c', 'l', 'i',
>   '/', 'c', 'l', 'i', '.', 't', 's', ' ', '-', ' ', '-', '-',
>   'f', 'u', 'z', 'z',
>   ... 6 more items
> ]
> Parsed word: ???
> Parsed word: --fuzzy
> Fuzzy option detected
> result: [ '???' ]
> Parsed word: -
> Parsed word: /workspaces/abr-geocoder/src/cli/cli.ts
> Parsed word: /workspaces/abr-geocoder/node_modules/.bin/ts-node
> Final parsed args: [
>   '/workspaces/abr-geocoder/node_modules/.bin/ts-node',
>   '/workspaces/abr-geocoder/src/cli/cli.ts',
>   '<stdin>',
>   '--fuzzy',
>   '???'
> ]
> ```

シェルのワイルドカード展開で`src`ディレクトリが当たってしまってる
